export const PROGRESS_TO_NEXT_DAY = 'PROGRESS_TO_NEXT_DAY';
export const PROGRESS_TO_NEXT_PHASE = 'PROGRESS_TO_NEXT_PHASE';
export const EXPLORE_SOURCE = 'EXPLORE_SOURCE';
export const LEARN_COMPETENCY = 'LEARN_COMPETENCY';
export const COMPLETE_JOB = 'COMPLETE_JOB';